### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by mazzola** [mazzola/dnd-beyond-dice-chrome-extension#12]
As a developer, whenever I make changes to the source files, I want the chrome extension to automatically be updated so that the development loop is faster.

**Comment by mikemfleming** [comment]
With Parcel it was possible to do a janky version (just refreshing the page) of this because
* it has a ws server that emits messages when it reloads
* you are able to specify the port so the client side knows where to connect

We absolutely should be able to do this with Webpack. Here are some possibilities:
* [webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader)
* [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server)

**Comment by mikemfleming** [comment]
After reassessing, there's some serious issues with the implementation of the web-extension-reloader package. They were there before when I first switched us over to webpack but the additional time to look into it wasn't fruitful.

The extension reloader needs to update some of its dependencies because it's not working with the current version of webpack. It's a bit crufty with several forks and hasn't been maintained in a year+ so I think I'd prefer to try a home rolled solution for this.
